name: Continuos Integration
on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  push:

jobs:
  tests:
    uses: ./.github/workflows/_tests.yml
    secrets:
      RAILS_MASTER_KEY_TEST: ${{ secrets.RAILS_MASTER_KEY_TEST }}

  code_quality:
    uses: ./.github/workflows/_linters.yml
